#include <iostream>
using namespace std;
main(){
	int a ;
	int b ;
	int c ;
	int d ;
	int e ;
	int f ;
	int g ;
	int h ;
	int i ;
	int j ;
	int k ;
	int l ;
	int m ;
	int n ;
	int o ;
	int multiply ;
	int add ;
	int subtract ;
	int total ;
	cout << "Number 1: " ;
	cin >> a ;
	cout << "Number 2: " ;
	cin >> b ;
	cout << "Number 3: " ;
	cin >> c ;
	cout << "Number 4: " ;
	cin >> d ;
	cout << "Number 5: " ;
	cin >> e;
	cout << "Number 6: " ;
	cin >> f ;
	cout << "Number 7: " ;
	cin >> g ;
	cout << "Number 8: " ;
	cin >> h ;
	cout << "Number 9: " ;
	cin >> i ;
	cout << "Number 10: " ;
	cin >> j ;
	cout << "Number 11: " ;
	cin >> k ;
	cout << "Number 12: " ;
	cin >> l ;
	cout << "Number 13: " ;
	cin >> m ;
	cout << "Number 14: " ;
	cin >> n ;
	cout << "Number 15: " ;
	cin >> o ;
	add = a+b+c+d+e ;
	multiply = f*g*h*i*j ;
	subtract = k-l-m-n-o ;
	total = (add+multiply)-subtract ;
	cout <<	"The final result is: " << total ;
}